### ISSUE TITLE
Make cuzzle optional

### ISSUE THREAD

**Issue by Avariya** [csarrazi/CsaGuzzleBundle#178]
Would be nice to have possibility to make cuzzle library optional. It has some bugs and to be honest guzzle bundle will work proper without it.
In case if deactivated cuzzle - do not show command point at profiler.

**Comment by Avariya** [comment]
https://github.com/csarrazi/CsaGuzzleBundle/pull/179
I'm not sure how to check is suggestion was accepted by developer. So make it in class_exists way.
If I'm not right - let me know.

**Comment by csarrazi** [comment]
Well, there are multiple approaches.

* Using dependency injection to inject the class, and detect whether the class is present or not at compiling rather than runtime.
* Detect whether the class is here during runtime (in the constructor, like you did).
* Ask the developer for explicitly enabling / disabling support for cuzzle in the configuration.

I have a preference for option 2. Not much of a difference with what you already did. The only difference is that the formatter would be exposed as an optional service, injected by the bundle's extension.

**Comment by Avariya** [comment]
>> The only difference is that the formatter would be exposed as an optional service
Yes. It is better way, but in this case would be nice to create cuzzle-bundle. But I'm to lazy for this. =)

**Comment by csarrazi** [comment]
Fixed by #179
