### ISSUE TITLE
[Cache][History] Correlation ID is preventing caching of request responses

### ISSUE THREAD

**Issue by aliebing** [csarrazi/CsaGuzzleBundle#184]
Hi, I'm using csa guzzle @stable with guzzle 6.2
After configure cache with DoctrineAdapter and FileSystemCache I noticed, cache is saving every time with new key but not reading.
The reason is: HistoryMiddleware is also loaded with Header key X-Guzzle-CorrelationId and uniqid on every request. So the request header value is every time new. So the cache key is also new with this key strategy:
public function filename(RequestInterface $request)
    {
        return md5(serialize([
            'method' => $request->getMethod(),
            'uri' => $request->getUri(),
            'headers' => $request->getHeaders(),
        ]));
    }
Wy is it so?

Cache with DoctrineAdapter is also running with old one csa 2.0.6

**Comment by csarrazi** [comment]
The idea behind the CorrelationId was a workaround behind the fact that PSR-7 messages are immutable, and provide no way of tracing what happens to the request object, from start to finish. I guess the mock middleware and associated storage were updated to ignore the new header, but unfortunately the cache middleware wasn't (and actually isn't able to ignore headers at all).

I think we need to add more common logic between the cache adapters and the mock storage adapter.

In the mean time, in order to fix this, you could extend the cache handler to ignore the X-Guzzle-CorrelationId header for each request (before calculating the filename).

**Comment by aliebing** [comment]
Ok, I guess switch to 2.0.6 version is not a option. So I will override DoctrineAdapter with full implementation of methods in it with remove Header value:
$request->withoutHeader(HistoryMiddleware::CORRELATION_ID_HEADER);

**Comment by csarrazi** [comment]
That would be the way to go. However, you would only need to do something like that:

```php
class MyCustomAdapter extends DoctrineAdapter
{
    public function fetch(RequestInterface $request)
    {
        $request = $request->withoutHeader(HistoryMiddleware::CORRELATION_ID_HEADER);

        return parent::fetch($request);
    }

    public function save(RequestInterface $request, ResponseInterface $response)
    {
        $request = $request->withoutHeader(HistoryMiddleware::CORRELATION_ID_HEADER);
        parent::save($request, $response);
    }
}
```

**Comment by aliebing** [comment]
In this case the profiler doesn't work correctly and its loading from cache in profiler shows me the request with requested time?!

**Comment by csarrazi** [comment]
I changed the title of the issue to better reflect the actual bug. I am not satisfied with the way the correlation between requests is done with the Correlation ID. Like you said, I'm actually considering reverting this feature, as it seems to be causing more issues than it solves, and it clearly hasn't been tested enough.

**Comment by csarrazi** [comment]
@aliebing I am currently working on a workaround for this issue. Should be fixed by end of week!

**Comment by csarrazi** [comment]
Fixed. Correlation ID does not exist anymore.

**Comment by thim81** [comment]
When will this fix be released?

**Comment by csarrazi** [comment]
You should be able to use `2.2@alpha`. The pull requests were made against the `master` branch, which is the current development branch for 2.2.

**Comment by giorgiosironi** [comment]
The `X-Guzzle-CorrelationId` header seems to have appeared between `2.1.0` (excluded) and `2.1.2`, breaking both caching and the `MockMiddleware` as requests were not matched anymore due to the expected requests not having that header.

To conform to semantic versioning, it would be correct to release a `2.1.x` without `X-Guzzle-CorrelationId`, otherwise anyone upgrading with `^2.1` may break.

**Comment by csarrazi** [comment]
Hi @giorgiosironi!

Actually, the term "minor" is related to the second number in semver, not the third one (which is called "patch"). This means that the fix should be released in 2.2, which has been my intent from the start.

Unfortunately, I do not have enough time to work on the remaining features which I had planned for 2.2, so I will delay them until 2.3, and release the current 2.2-alpha1 version as 2.2.0.

**Comment by giorgiosironi** [comment]
Ah right, so `2.2` it is. We now have pinned `2.1.0` so that we do not experience the problem, thanks.

**Comment by csarrazi** [comment]
You can switch to 2.2. 2.2 is entirely backward-compatible with 2.1, and fixes a few other issues, related to edge cases, when Guzzle is not able to connect to the server.
