### ISSUE TITLE
missing class logger

### ISSUE THREAD

**Issue by cordoval** [csarrazi/CsaGuzzleBundle#23]
please tag it else it straight gives an error when using the last tagged version ~1.2.5

thanks

**Comment by csarrazi** [comment]
Can you describe the issue a little more with an anonymized config for the bundle, so I can reproduce it?

**Comment by csarrazi** [comment]
Ping @cordoval. Did you add any configuration, to obtain this error?

**Comment by cordoval** [comment]
hmm i cannot remember right the second because i am in the middle of a frenzy PR, but i can check tonight perhaps, definitely i don't create issues lightly :blush: i wonder how can i remind myself of this later on tonight ... ok

**Comment by csarrazi** [comment]
No prob! This will be very helpful, as I cannot reproduce this issue locally.

**Comment by cordoval** [comment]
try to rm -rf vendor on the packages as well and start clean, you will see this unless it has been fixed by the tagging

another thing i see it is troublesome is the fact you are using minimum stability dev which should be set to stable

I have a Pr on a project where i use this, but i have not gotten to it yet, but i am sure i will find more issues as i revisit the PR

**Comment by csarrazi** [comment]
Minimum stability dev has no incidence on a parent project, as the parent project forces the minimum stability for all of its dependencies, unless you override the dependency using stability flags (`@dev`, etc.).

In a general matter, in a autonomous project (CLI tool, web application), the stability should always be set to `stable` (or omitted). For libraries, you need to be able to build them against unstable dependencies.

As you may see, the `.travis.yml` is configured to build the project against multiple versions of dependencies (minimum versions, as well as latest versions). This is done in order to prepare for upcoming releases of Symfony (`2.7` to `3.0`), and ensure compatibility with all versions (currently, CsaGuzzleBundle supports Symfony, starting from version `2.3`).

However, this is another matter. I'll take a look at the issue as soon as I can identify the problem.

There was an issue with releases `v1.2.2`, `v1.2.3` and `1.2.4` with a missing class (see #18), which was fixed in `v1.2.5`.

These releases actually break if you enable the logger subscriber, without adding Guzzle's logger subscriber as a dependency.

See

* https://github.com/csarrazi/CsaGuzzleBundle/compare/v1.2.1...v1.2.2 The faulty code is here
* https://github.com/csarrazi/CsaGuzzleBundle/compare/v1.2.4...v1.2.5 The fix is here

If you can't replicate this issue with `1.2.5+` or the master branch, then I'll mark this as a duplicate of #18 :)

**Comment by cordoval** [comment]
correct i was in a previous version or such, so closing but yeah would be nice to know for sure the reason. :+1:

**Comment by cordoval** [comment]
duplicate of #18
