### ISSUE TITLE
New release to support twig 3 and symfony 5

### ISSUE THREAD

**Issue by vchebotarev** [csarrazi/CsaGuzzleBundle#257]
Hello.
Is it possible to create new release ?
I saw there was an idea to create 4.0 ... but what about creating 3.2 with twig 3 and symfony 5 support ?
Maybe "community" can help ?

**Comment by niconoe-** [comment]
Hi.
I'm also waiting for a symfony 5 support for my projects using CsaGuzzleBundle. I like @vchebotarev idea to rollout a 3.2 while working on 4.0 and I can help if there is a need of.
Looking at the current master, only a little style issue is blocking since November the 12th but tests looks like very good and a potential version 3.2 looks like stable. Are you willing to add some new features or review something in which we could help?

Thanks a lot.

**Comment by csarrazi** [comment]
Hi @vchebotarev @niconoe- . The next release will still be a minor release (3.1).

No new features have been added for a while, and I very few contributions have been made over the last months. Overall, there's no work to do other than creating a signed tag, but I currently do not have a machine on which I can install the project. In the meantime, please just use `4.0@dev`, which *does* have support for Symfony 5.0 and Twig 3.0.
