### ISSUE TITLE
The request's number icon should be red when there is an error

### ISSUE THREAD

**Issue by salahm** [csarrazi/CsaGuzzleBundle#8]
On the sidebar, the guzzle request's number should be red (when there is at least one error) as it is on the profiler top bar.

![image](https://cloud.githubusercontent.com/assets/1071005/5916031/a01cb9be-a60c-11e4-9e83-58d859321145.png)

**Comment by csarrazi** [comment]
After inspecting the issue, no other bundle bundle actually displays error-like elementns in the left menu with a different color in case there is an error. That's actually because there is no CSS class yet to handle this.

As I think this should be addressed in symfony/symfony as a DX issue, I'll try to create a PR to add the new feature during the week.

**Comment by csarrazi** [comment]
Fixed by #68
